version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-1
    networks:
      - spring-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-1
    networks:
      - spring-network
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    image: my-spring-app
    container_name: spring-app
    networks:
      - spring-network
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["--spring.profiles.active=consumer"]
    # environment:
    #   SPRING_PROFILES_ACTIVE: consumer

networks:
  spring-network:
    driver: bridge
