server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  application:
    name: pro


  datasource:
    url: jdbc:mysql://my8003.gabiadb.com:3306/jmdb
    username: jmhost
    password: jaemin171717
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000
      maximum-pool-size: 5
      pool-name: jm-admin-pool

  #rabbitMQ
  main:
    rabbitmq:
      host: localhost
      port: 5672
      username: jaemin
      password: jaemin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true
        id:
          new_generator_mappings: false

  web:
    resources:
      add-mappings: false


  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
  cache:
    type: redis
    redis:
      use-key-prefix: true
      cache-null-values: true


#mybatis
#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: false
#logging:
#  level:
#    jdbc.sqlonly: INFO


